spring:
  application:
    name: cse

logging:
  level:
    root: DEBUG
    org.mongodb: INFO
    org.springframework.web: INFO
    dev.morphia.mapping.codec.pojo: INFO
  file:
    name: "./logs/cse.log"

server:
  error:
    path: "/error"
    whitelabel:
      enabled: false
  port: 8081